### ISSUE TITLE
Error when checking : expected x_generator to have shape (None, 3, 32, 32) but got array with shape (1, 3, 128, 128)

### ISSUE THREAD

**Issue by eeric** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#11]
Traceback (most recent call last):
  File "models.py", line 720, in <module>
    srgan_network.train_full_model(coco_path, nb_images=80000, nb_epochs=10)
  File "models.py", line 432, in train_full_model
    self._train_model(image_dir, nb_images, nb_epochs, load_generative_weights=True, load_discriminator_weights=True)
  File "models.py", line 612, in _train_model
    X_pred = self.generative_model_.predict(x, self.batch_size)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/engine/training.py", line 1179, in predict
    check_batch_dim=False)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/engine/training.py", line 111, in standardize_input_data
    str(array.shape))

Exception: Error when checking : expected x_generator to have shape (None, 3, 32, 32) but got array with shape (1, 3, 128, 128)

That contradicts Scaling 32*32 in srgan_network = SRGANNetwork(img_width=32, img_height=32, batch_size=1) in 711th line, downscale to 64*64 and upscale to 256*256?
So that is modified 64*64 in srgan_network = SRGANNetwork(img_width=32, img_height=32, batch_size=1), isn't it?

**Comment by titu1994** [comment]
I pushed a fix for that bug a week ago. Download the latest repository.
