### ISSUE TITLE
AttributeError: 'module' object has no attribute 'find_graphviz'

### ISSUE THREAD

**Issue by SeekPoint** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#16]
rzai@rzai00:~/prj/Super-Resolution-using-Generative-Adversarial-Networks/tests$ CUDA_VISIBLE_DEVICES=1 python3  benchmark_test.py 
Using Theano backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/printing.py", line 28, in <module>
    import pydot_ng as pd
ImportError: No module named 'pydot_ng'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmark_test.py", line 1, in <module>
    from keras.layers import Input
  File "/usr/local/lib/python3.4/dist-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python3.4/dist-packages/keras/backend/__init__.py", line 61, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python3.4/dist-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/usr/local/lib/python3.4/dist-packages/theano/__init__.py", line 74, in <module>
    from theano.printing import pprint, pp
  File "/usr/local/lib/python3.4/dist-packages/theano/printing.py", line 35, in <module>
    if pd.find_graphviz():
AttributeError: 'module' object has no attribute 'find_graphviz'
rzai@rzai00:~/prj/Super-Resolution-using-Generative-Adversarial-Networks/tests$

**Comment by titu1994** [comment]
You must be trying to plot the model ? You will need to `pip install pydot-ng`. If that doesn't work, try `conda install pydot-ng`
