### ISSUE TITLE
I got error when I run python

### ISSUE THREAD

**Issue by dlongry** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#21]

**Comment by dlongry** [comment]
I got the error message as below：
Using Theano backend.
Generator weights loaded.
Training SRGAN network
()
Epoch : 1
Found 0 images belonging to 0 classes.
Traceback (most recent call last):
  File "models.py", line 780, in <module>
    srgan_network.pre_train_srgan(coco_path, nb_images=80000, nb_epochs=1)
  File "models.py", line 439, in pre_train_srgan
    load_generative_weights=True)
  File "models.py", line 507, in _train_model
    target_size=(img_width, img_height)):
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 822, in next
    index_array, current_index, current_batch_size = next(self.index_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 645, in _flow_index
    current_index = (self.batch_index * batch_size) % n
ZeroDivisionError: integer division or modulo by zero

Do you know the reason of it？thanks a lot！

**Comment by dlongry** [comment]
OK ，the reason is the error of  images' path .Say the folders are at /home/data/images/*.jpg, then provide the path as : /home/data
