### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by hua0719** [titu1994/Super-Resolution-using-Generative-Adversarial-Networks#29]
Traceback (most recent call last):
  File "D:/python file/Super-Resolution-using-Generative-Adversarial-Networks-master/models.py", line 10, in <module>
    from keras_ops import fit as bypass_fit, smooth_gan_labels
  File "D:\python file\Super-Resolution-using-Generative-Adversarial-Networks-master\keras_ops.py", line 5, in <module>
    from keras.engine.training import objectives, standardize_input_data, slice_X, \
ImportError: cannot import name 'objectives'

**Comment by mbeach42** [comment]
"objectives" is depreciated and has been replaced by "losses"
